concurrent = 8
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "minttea-nixos-desktop-dind"
  url = "https://gitlab.com"
  id = 47808118
  token = "glrt-NjpCmKgCyrdrX364Dt9gOG86MQpwOjM2Z292CnQ6Mwp1OjU5NXMwFw.01.1i0giq1b7"
  token_obtained_at = 2025-06-13T00:17:07Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    host = "unix:///var/run/podman/podman.sock"
    tls_verify = false
    image = "quay.io/podman/stable"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    environment = [ "DOCKER_HOST=\"tcp://docker:2375\"", "DOCKER_TLS_CERTDIR=\"\"" ]
    volumes = ["/cache", "/certs" ]
    shm_size = 0
    network_mtu = 0
    [[runners.docker.services]]
      name = "docker:27-dind"
      alias = "docker"
  [runners.feature_flags]
    FF_NETWORK_PER_BUILD = true
