# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/fb7624ac-190d-40a8-aed8-2bba14c69a7c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/1CB9-3587";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [
    {
      device = "/swapfile";
      size = 16 * 1024; # 16 GiB
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  #networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;
  hardware.enableAllHardware = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = true;

  #boot.kernelParams = [ "amd_pstate=active" ];
  powerManagement.enable = true;
  powerManagement.cpuFreqGovernor = "schedutil";
  powerManagement.powertop.enable = true;

  services.thermald.enable = true;
  services.tlp.enable = true;
  services.tlp.settings = {
    TLP_ENABLE = true;

    # Stop charging at 80%
    STOP_CHARGE_THRESH_BAT0 = 80;
    # Start charging when the level drops to 75%
    START_CHARGE_THRESH_BAT0 = 75;

    # Set CPU to powersave on battery
    CPU_DRIVER_OPMODE_ON_BAT = "active";
    CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
    CPU_ENERGY_PERF_POLICY_ON_BAT = "power";
    PLATFORM_PROFILE_ON_BAT = "quiet";
    CPU_BOOST_ON_BAT = 0;
    CPU_MIN_PERF_ON_BAT = 0;
    CPU_MAX_PERF_ON_BAT = 50;
    CPU_SCALING_MIN_FREQ_ON_BAT = 0;
    CPU_SCALING_MAX_FREQ_ON_BAT = 2000000; # limit to 2 GHz on battery

    # Set CPU to performance on AC
    CPU_DRIVER_OPMODE_ON_AC = "guided";
    CPU_SCALING_GOVERNOR_ON_AC = "schedutil";
    CPU_ENERGY_PERF_POLICY_ON_AC = "balance_performance";
    PLATFORM_PROFILE_ON_AC = "balanced";
    CPU_BOOST_ON_AC = 1;
    CPU_MIN_PERF_ON_AC = 0;
    CPU_MAX_PERF_ON_AC = 100;
    CPU_SCALING_MIN_FREQ_ON_AC = 0;
    CPU_SCALING_MAX_FREQ_ON_AC = 9999999;

    # only enable wifi on startup
    DEVICES_TO_ENABLE_ON_STARTUP = "bluetooth wifi wwan";
    DEVICES_TO_DISABLE_ON_STARTUP = "";

    #DEVICES_TO_DISABLE_ON_LAN_CONNECT = "wifi wwan";
    #DEVICES_TO_DISABLE_ON_WIFI_CONNECT = "wwan";
    #DEVICES_TO_DISABLE_ON_WWAN_CONNECT = "wifi";

    #DEVICES_TO_ENABLE_ON_LAN_DISCONNECT = "wifi wwan";
    #DEVICES_TO_ENABLE_ON_WIFI_DISCONNECT = "";
    #DEVICES_TO_ENABLE_ON_WWAN_DISCONNECT = "";

    #DEVICES_TO_ENABLE_ON_AC = "bluetooth wifi wwan";
    #DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE = "";


    RUNTIME_PM_ON_AC = "on";
    RUNTIME_PM_ON_BAT = "auto";

    RUNTIME_PM_DISABLE = "08:00.3 08:00.4";
    RUNTIME_PM_DRIVER_DENYLIST = "mei_me nouveau radeon xhci_hcd";

    PCIE_ASPM_ON_AC = "default";
    PCIE_ASPM_ON_BAT = "powersave";
  };
}
